### ISSUE TITLE
Add support for ClientID to DHCP

### ISSUE THREAD

**Issue by eyakubovich** [containernetworking/cni#17]
With ipvlan, all interfaces will share the MAC address so the DHCP server will return the same lease. Need to add support for ClientID (DHCP option 61). The value can be ContainerID by default but over-rideable via `CNI_ARGS`.

**Comment by eyakubovich** [comment]
Ok, this won't work. Adding support for ClientID option is still a good idea but DHCP won't work with ipvlan. DHCPOFFER will come back with some IP but ipvlan machinery won't yet know to which enslaved device to forward it to.

**Comment by dcbw** [comment]
@eyakubovich can you describe a bit more what your problem is?  I've had ipvlan working with multiple OpenShift containers in the past.  There are at least a couple of caveats:

1) you need to use the 'broadcast' option with the DHCP client
2) the client ID must be different between each ipvlan interface
3) VirtualBox's DHCP server doesn't support client IDs so it'll never work with ipvlan
4) You obviously need to use L2 ipvlan devices, not L3 ones
5) you also may need to set rp_filter on the parent interface

I'll bet your issue is (1) and/or (5).

**Comment by dcbw** [comment]
https://github.com/containernetworking/plugins/pull/217

**Comment by deliciouslytyped** [comment]
@dcbw  thank you for your answer here, it helped me a lot by pointing me in the right direction. Details at https://github.com/NixOS/nixpkgs/pull/48753#issuecomment-823768685
