### ISSUE TITLE
RFE: provide bash based cni plugin reference implementation

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [containernetworking/cni#265]
1) since "it takes forever" to incorporate new features and options into existing `rkt/cni` network plugins, we suggest to include into `cni` distribution a bash based cni plugin reference implementation, so people can start experimenting on their own faster

2) for example, here is a bridge+dhcp plugin 
https://gist.github.com/Andrei-Pozolotin/6bc4f2caa18700cdd94d910e588a555c
with support for additional `CNI_ARGS`:
- `machine_name`: fqdn host name override (included in dhcp request, option 81)
- `machine_mac`: ethernet address override (used for dhcp assignment)

3) usage:

```
rkt run \
   --insecure-options=all \
   --net="bridge.sh:machine_name=aci-serv;machine_mac=12-34-56-78-90-ab" \
   docker://carrotgarden/aci-serv
```

dhcp option 81: https://tools.ietf.org/html/rfc4702#page-4

**Comment by leodotcloud** [comment]
@Andrei-Pozolotin 

The current CNI repo already has a `scripts` folder which shows a very simple implementation of a CNI plugin. Here: https://github.com/containernetworking/cni/blob/master/scripts/exec-plugins.sh

When I first started out on my path to implement a CNI plugin, these scripts were really helpful to play with and understand the CNI spec/API. Also looking at few other CNI plugins really fast tracked my comprehension.

The CNI repo currently has few binaries in the `plugins` folder like bridge, loopback, etc. IMHO, the intention of these provided binaries is not to address all possible requirements of every user but to provide a handful of fully working sample implementations. If these binaries are useful and complete enough by themselves, they can be used as is otherwise it's up to the author of CNI plugin to fully customize to their needs. You can look at some other CNI plugins to see how they are implementing their custom needs/requirements: 
- https://github.com/projectcalico/calico-cni
- https://github.com/weaveworks/weave-cni
- https://github.com/rancher/rancher-cni-ipam

If you have any further questions/comments, please feel free to update the issue. Otherwise, could you please close the issue?
