### ISSUE TITLE
Versioning!

### ISSUE THREAD

**Issue by rosenhouse** [containernetworking/cni#266]
I'm opening this issue so we can track and discuss work on versioning as first discussed at the [CNI meeting on 2016-06-29](https://docs.google.com/document/d/1_FDwd1QuFRxT_f40Wq4L6Q2jL2jqIDOoVhNBB26TViE/edit#heading=h.h0y3jbyyk1iw).  This is in part to address current confusion over versioning (e.g. https://github.com/containernetworking/cni/issues/150).

I will update this issue as we make progress.  Please leave general feedback here, and use the PRs for specific code review feedback.

Complete:
- ~~add `VERSION` command, #267~~
- ~~Plugin and runtime library support for plugins to report support for multiple versions of the CNI spec, #287~~
- ~~Plugins validate `cniVersion` of their input config, #296~~
- ~~Automated tests verify that `libcni` is backwards compatible with legacy plugins, #301~~

In flight:
- Modify #145 to use new versioning tooling.

Proposed next steps:
- Update spec with answers to these questions:
  - what do plugin authors need to do about versioning?
  - what do container runtime maintainers need to do about versioning?
  - under what circumstances will the spec version will change?
- Automated tests in the CNI repo verify version correctness of the plugins that we maintain.
- The runtime-facing `libcni` functions (`AddNetwork` and `DelNetwork`) reconcile the versions:
  - Reported by the plugin's VERSION command
  - Contained in the config
  - In use by the `libcni` package
  
  So that exactly one of the following occurs:
  - **Either**: the plugin is called with config matching a version in its VERSION list
  - **Or**: the function's caller receives an error that would be meaningful to a user, e.g. 
    
    ```
     the CNI library in use (spec 0.2.0) is not compatible with the plugin "foobar"
     (plugin reports compatibility with spec versions [0.5.0, 0.6.0])
    ```

References:
- Draft [document collecting uses cases](https://docs.google.com/document/d/1fKRHQ10vDgbGED4NwJU_EbPbt-J0fK8prHod_6yVFf0/edit#heading=h.hf1r2to8das2)
- [CNI meeting notes](https://docs.google.com/document/d/1_FDwd1QuFRxT_f40Wq4L6Q2jL2jqIDOoVhNBB26TViE/edit)

**Comment by bboreham** [comment]
I'd like to suggest that failure to handle the VERSION command shall be interpreted the same as returning "0.1.0", so that older plugins do not become immediately useless.

**Comment by squaremo** [comment]
> Given that it was never implemented by the plugins in this repo, and it is obviated by the VERSION command, should it be deprecated?

I don't think including `cniVersion` in responses is obviated by the version command, or at least it shouldn't be. But it _should_ be obviated by plugins behaving correctly with respect to versioning, that is

 * refusing to service a request of a version that the plugin doesn't support
 * returning a response of the same version as the request

**Comment by bboreham** [comment]
ok, that's a better analysis.

**Comment by squaremo** [comment]
My jumble of change. Summary:

 * A server must refuse to process requests for a newer protocol than it
knows. Otherwise, the client will get unexpected results.
 * A server must validate the version of the request before it does
anything else. That's to make sure it responds with the correct error
if it cannot serve the version requested -- otherwise it might crash
on getting an unexpected input, for example. (This is a good reason to
have `CNI_VERSION`)
 * An application should use the lowest protocol version that it
needs. This has the best chance of succeeding -- and is also the
default situation.
 * The protocol version should change only when there is an incompatibility.
There is no reason to signal anything, otherwise.
 * It should be possible to update the client library
without changing which protocol version you use.

The rest:

CNI is a client/server protocol, with the runtime as
client and the plugin as server. In general: a newer client may ask
things that the older server cannot provide (otherwise, why is it
newer?).

Usually, the way these are versioned is that a newer server can deal
with older clients, but a newer client cannot deal with older
servers. The use cases 1) and 2) in the doc correspond to these two cases.

A server must refuse to process requests for a newer protocol than it
knows. Otherwise, the client will get unexpected results.

Alternative: a server can return a "best effort" answer corresponding
to a older version of the protocol. This is bad because it puts the
burden on the application developer to notice this, and try to use the
result. It is better to assume that the newer protocol is being used
because it has features necessary for the application; i.e., that
nothing from an older protocol will suffice.

A server must validate the version of the request before it does
anything else. That's to make sure it responds with the correct error
if it cannot serve the version requested -- otherwise it might crash
on getting an unexpected input, for example.

An application should use the lowest protocol version that it
needs. This has the best chance of succeeding -- and is also the
default situation.

On version probes: these might be useful if the application wants to
use the newer protocol, but can work around the old; or, if the
application will use the newer protocol later, but wants to bail
early.

A version probe should be the only time the server needs to provide
version information in its reply; otherwise it can just refuse or
comply. NB failing a version probe should be an error in the library, so that
servers from before version probes will mostly do the right thing by default.

On versioning: Why change the version? Often, saying "I don't
understand this", i.e., just returning an error, is enough. But it's
useful to know what the remedy is, so versioning says "I don't
understand this because it's new to me".

The exception is when something looks the same but is interpreted
differently. For example, a kind of request (`ADD`). Here the client
must know that its request will be processed as it expects, and it
will get back a result of the kind it expects.

The version should change only when there is an incompatibility.
There is no reason to signal anything, otherwise.

On versioning config: the payload is part of the request, and the
config is part of the payload. So it's important that it is
versioned. We can help here by making sure in the client library (for
runtimes) that configs are validated against the version of the
protocol in use. It is a bit tricky, because often you'll have a
config for the newer version, but only need to use _older_ API
requests. We may be able to help by providing helpers for downgrading
configs -- but only if that's possible to do
unambiguously. Ultimately, it is up to the plugin to say whether it
can process the config given, since each plugin has its own
specialised parameters.

How to make this easy for runtime developers? Mostly by making it easy
to switch versions. It should be possible to update the library
without changing which protocol version you use, so you can get
improvements without passing on an upgrade headache to your users.
One way to do this is to have distinct packages for protocol versions.

**Comment by dcbw** [comment]
@rosenhouse we also agreed IIRC that plugins should return a response according to the version of configuration they were given, right?  eg if your plugin supports [ 0.1.0, 0.2.0, 0.3.0 ] then your plugin needs to be able to return a response according to any of those API versions.  This implies that the incoming configuration needs a "cniVersion" field so the plugin knows what API version to return the result in.  This should be reflected in whatever PR comes out of this and in SPEC.md.

@bboreham While cniVersion in responses is indeed redundant with the cniVersion in the incoming config, I still think it's useful declarative information, and helps debug plugin errors.

**Comment by dcbw** [comment]
Another aspect of this is sub-plugins, like the IPAM plugins that core plugins call.  We obviously expect the core plugins to now call VERSION on the sub-plugins and do some basic validation to ensure that the incoming config is compatible with the version list the sub-plugin returns.  But that's not reflected anywhere in delegate.go/exec.go yet, so that code needs to be written.

**Comment by rosenhouse** [comment]
Thanks to everyone for the feedback so far.  I've opened #287 with the next small step in this effort.

**Comment by rosenhouse** [comment]
@dcbw brought up an interesting point in https://github.com/containernetworking/cni/pull/287#discussion_r77420159 that I'd like to bump up to this higher-level conversation.  To paraphrase: **what relationship, if any, should the version of the CNI spec have to our [git tags](https://github.com/containernetworking/cni/tags) and [github releases](https://github.com/containernetworking/cni/releases)?**

This matters because *contributors and maintainers need guidelines for when the CNI spec version number is supposed to change*.

A few options:

1. The two version numbers are totally unrelated.  They can and will change independently.

2. The two version numbers are kept exactly equal.

3. They are related in some meaningful way.  For example

   a. The CNI spec version `0.6` might be used by CNI library releases `0.6.0`, `0.6.1` and `0.6.2`.

   b. Alternately CNI spec version `0.6` might be used by library releases `0.6-0.0.0`, `0.6-0.1.0`, and `0.6-0.2.0`

4. Stop cutting github releases and deprecate the existing ones.   The only CNI "version" is the spec version.  Plugin and runtime developers are encouraged to build against the `master` branch.

The big drawback of (1) is that it will be confusing for everyone.  @dcbw also pointed out that it may lead to rapid inflation of the spec version.

The drawback of (2), IMHO, is that it conflates two different things that we may want to increment independently.  For example, a patch to the CNI library which fixed a bug in a core plugin could be merged but not released until we'd also bumped the CNI spec version.  That would violate @squaremo's recommendation above:
> the version should change only when there is an incompatibility. There is no reason to signal anything, otherwise.

The drawback of (3)(a), IMHO, is that we may surprise library consumers: a breaking change to the library that didn't change the spec would only increment the patch version, i.e. `0.6.3 --> 0.6.4`.  While SemVer does [allow arbitrary changes in behavior within the `0.x.x` version series](http://semver.org/#spec-item-4), nevertheless, consumers of the CNI library may not appreciate such things.

The drawback to (3)(b) is that it's a lot of numbers and may be confusing.

The drawback to (4) is that it may be disruptive to some CNI consumers.  (Just guessing -- CloudFoundry doesn't track CNI releases, we just vendor this repo as a submodule).

Thoughts?

**Comment by rosenhouse** [comment]
One other issue to consider (which motivated this topic): can & should the spec version change multiple times between github releases?  

Put another way: does every spec-changing PR need to include a spec version bump?  Or can the 2nd and 3rd PRs on a fresh spec version get away without bumping the version?

**Comment by squaremo** [comment]
> The drawback to (4) is that it may be disruptive to some CNI consumers. (Just guessing -- CloudFoundry doesn't track CNI releases, we just vendor this repo as a submodule).

I think this is what people using Go will do anyway -- they may vendor new versions at release points, or just find the commit nearest master that compiles and works, and stick with it until it doesn't.

**Comment by squeed** [comment]
Can we close this?

**Comment by rosenhouse** [comment]
Indeed we can!
