### ISSUE TITLE
RFE: dhcp plugin: support dhcp options via cni_args

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [containernetworking/cni#268]
dhcp options in general:
https://en.wikipedia.org/wiki/Dynamic_Host_Configuration_Protocol#DHCP_options

dhcp option 81 in particular:
https://tools.ietf.org/html/rfc4702#page-4
https://github.com/containernetworking/cni/issues/265

**Comment by leodotcloud** [comment]
@Andrei-Pozolotin 
Please see: https://github.com/containernetworking/cni/issues/265#issuecomment-256167719

As I mentioned there, it's up to the CNI plugin Author to customize. If you have a PR, please feel free to submit it, I am sure the maintainers would be more than happy to review and merge them. Otherwise, it's really not practical to address all possible requirements in the provided sample plugins.

Repeating:
FYI: CNI is a specification of the interface between the application and plugins. CNI repo has few sample plugins, it's not limited to only these but it's left to the imagination of the plugin authors to customize the implementations to their needs.


If this answers your question, could you please close the issue? Otherwise discussion/comments/questions are really welcome.

**Comment by bboreham** [comment]
DHCP plugin is now in a different repo https://github.com/containernetworking/plugins
