### ISSUE TITLE
How to find out ip address after it was assigned to a link?

### ISSUE THREAD

**Issue by dshulyak** [containernetworking/cni#281]
I am trying to understand who's responsibility is to store ip address after it was returned by cni ADD command. In kubernetes assigned ip needs to be known for multiple purposes and thus we need either:
1. store in database
   But what if assigned ip address is not static? With dhcp plugin it is certainly wont be
2. use other tools to query container namespace (in my case docker/rkt/nsenter)
   adds additional dependency either into container or host system (see https://github.com/kubernetes/kubernetes/pull/30225 for some context)
3. query application that returned ip

I like third way for several reasons:
- it hides the method which was used to assign ip address from cni clients, for example in bridge plugin application enters container network namespace and assigns ip to a link, and it is not my concern as a client
- cni is the source of ip, and in case of centralized control plane (dhcp for example) it would make sense to store it locally

Is there any plan/design how it will be addressed in long term?

**Comment by jellonek** [comment]
CNI plugin which is responsible for creating NS/veth/tap/interfaces returns information about interface and it's mac address.
AFAIR now there is no other way to verify which address is connected with that mac address other than arp query, because of mentioned possible dynamic change of values returned by plugin performing ADD command - which returns values from IPAM, which could be in meanwhile adjusted to new values - like in dhcp example.

AFAIK there was discussion how to deal with dhcp which requires long running client even when container is paused or even shutted down (but not garbage collected) - but don't know how this discussion ended.

So for this moment searching arp table for mac address seems to be quite ugly but effective solution, which bypasses missing interface accessible from CNI.

**Comment by dshulyak** [comment]
will it make sense to extend cni commands with GET that will have same input/output as ADD?
cc @steveeJ

**Comment by freehan** [comment]
> will it make sense to extend cni commands with GET that will have same input/output as ADD? but will be used only for information

Yeah. Something like a STATUS command would be great.

**Comment by leodotcloud** [comment]
@dshulyak 
Here are my 2 cents:
CNI plugin invocations are ephemeral. Once they are invoked with their input parameters, they do their job and return the information. They are short lived, which means the plugins rely on some sort of external database or micro service to handle the state and other meta information. If the information is external to the plugin, its logical to have query interface to the external entity rather than a query interface to the network plugin. If you look at other CNI plugin implementations, the information is stored in etcd or some other sort of database. When I implemented a CNI plugin, this necessary information is retrieved from our metadata server. ([See Source](https://github.com/rancher/rancher-cni-ipam/blob/master/ipfinder/metadata/ip_finder_metadata.go#L32))

Since the CNI plugins are invoked by container runtimes, which deal with a lot more complexity, they are anyways responsible for storing a lot of data, so it makes sense to keep this reponsibility at higher application level/layer.

My recommendation is to keep the CNI plugin API simple and not to add additional functionality unless it's really needed.

**Comment by bboreham** [comment]
Most current implementations can fetch the IP address assigned to a container by entering the namespace and examining the `eth0` device. No database calls are required. 

In my view It is reasonable to add GET to the API to allow for those implementations which do not support this pattern.

**Comment by dcbw** [comment]
libcni now caches the Result of the ADD operation and will return that Result when the CHECK command is called. That's effectively the same thing as GET. You can also use libcni to get the cached Result from the runtime.
