### ISSUE TITLE
Proposal: run CNI plugins as containers

### ISSUE THREAD

**Issue by bboreham** [containernetworking/cni#284]
## Overview

Current uses of CNI expect the plugin to be runnable as a process from a path on the host, e.g. `/opt/cni/bin/myplugin`.

However some recent OS platforms, e.g. CoreOS or Google Container-VM, discourage installing software in the filesystem, and prefer that everything be installed as a container.

To resolve this, it should be possible to run CNI plugins as containers.

This proposal really applies to callers of CNI plugins, such as Kubernetes or Mesos, that already know how to download and run containers.  I was encouraged to post in the CNI repo in order that it can be discussed across any of those systems, and reach common ground.
## Method

Instead of looking for an executable `/opt/cni/bin/myplugin`, the caller of the plugin would fetch an  image named `mycompany/myplugin`, would run the container with needed capabilities (e.g. `CAP_NET_ADMIN`) and appropriate environment variables.

The caller would pass the CNI network config JSON in via the container's stdin and read the result  from stderr as usual.
## Complications

One CNI plugin may call another, for example a network plugin calling an ipam plugin.  I can see three cases:
- the two plugins are shipped together, and one can call the other by
  exec-ing a file within the container filesystem.
- the first plugin is in a container, and the second is in the host
  filesystem.  The calling environment can bind-map that directory
  into the container's filesystem.  This requires that second plugin
  not have any dependencies (e.g. shared libraries) which are absent
  from the container's filesystem.
- both the first and the second plugin are shipped as containers,
  independently.  The calling environment could inject an executable
  into the container filesystem which understands how to run a plugin
  via the container runtime.
## Implications

Running CNI plugins as containers has no impact on the CNI spec: plugins still receive arguments and config in the same way, and return results in the same way.  The hard work should be all on the calling side, e.g. in Kubernetes or Mesos.  

CC @caseydavenport

**Comment by rosenhouse** [comment]
Interesting.   If I'm understanding correctly, the container runtime would always need to bind mount the netns of the target container, then volume mount that location into the container running the CNI plugin, so that the CNI executable is able to find that netns.  Or am I missing something?

I recognize that wouldn't be part of the CNI library, just trying to understand how it would all work.

**Comment by bboreham** [comment]
It could just run the container in the root namespace. In Docker terms, run with `--net=host`

Maybe also `--pid=host`

**Comment by rosenhouse** [comment]
Oh, right.  --pid=host would at least cover the runC case that I'm familiar with.  Thanks.

**Comment by dcbw** [comment]
Sounds more-or-less reasonable.  Implementation is going to be the interesting part.

But I'm not sure I agree there is no impact on the spec.  If we allow CNI plugins to execute sub-plugins (like IPAM plugins) that are not packaged in the container, we'd need to make CNI smarter about how to run plugins and pass in some helper that knows how to execute the sub-plugin.  And so-on, since the sub-plugin might also wrap another plugin, and those sub-sub-plugins might need to execute a container to.

Simplest thing for now is to require the CNI plugin and all other plugins that one may require to be bundled into the same container image.  That IMHO would require neither spec changes nor implementation changes in CNI, just changes in the runtimes that call them.  Let's take that step first and explore split-container plugins next?

**Comment by squaremo** [comment]
> If we allow CNI plugins to execute sub-plugins (like IPAM plugins) that are not packaged in the container, we'd need to make CNI smarter about how to run plugins and pass in some helper that knows how to execute the sub-plugin. And so-on, since the sub-plugin might also wrap another plugin, and those sub-sub-plugins might need to execute a container to.

This puts me in mind of the discussion around composing plugins, which has been on the back burner for a while. One option there is to use a trampoline to call plugins sequentially, instead of nesting them. I.e., if the state is threaded through plugins, rather than needing them to delegate to other plugins themselves, they can simply return control to the library, which can in turn ask the application how to run the next plugin.

**Comment by micw** [comment]
Thanks @bboreham to mention it here. The initial purpose of the container was just to create a way to deliver the reference plug-ins into kubernetes. But if this issue is fixed, it could also be applied to that image. Currently plug-ins that require the reference plug-ins (e.g. flannel) maintain their own copy of this plug-ins and install it into /opt/cni/bin - having a more official build would be a good thing.

**Comment by alexellis** [comment]
This issue is quite seasoned now. A 3 year old vintage. I was considering doing the same, but after trying to get containerd and Jess' netns tool to work I'm close to giving up thinking this may be a square peg/round hole situation. 

Will the container even see the local side of the bridge interface like cni0?

**Comment by bboreham** [comment]
I think the most likely change (some way in the future) will be the addition of a gRPC call interface for CNI, similar to CRI and CSI interfaces, in which case it would be feasible to run the plugin in a container.
