### ISSUE TITLE
Question: [CNI Spec- IPAM] Why the default gateway is not used to create a default route?

### ISSUE THREAD

**Issue by skysec** [containernetworking/cni#310]
The CNI Spec defines a "default Gateway", however, it doesn't instruct the CNI pluging to add any routes, however, in a DHCP configuration or even in a manual network configuration, a default gateway is used to configure a default route (no need to add an extra route). This breaks current network implementation, where only a gateway (DHCP option 3) is passed as an option to DHCP clients. If a default gateway is defined, then a default route should be created.

**Comment by eyz** [comment]
Per https://github.com/containernetworking/cni/blob/master/SPEC.md, this is a valid way to set a static route, but it does not work in my testing on Kubernetes 1.9.2 -
```
{
  "cniVersion": "0.3.1",
  "name": "wan",
  "type": "macvlan",
  // ipam specific
  "ipam": {
    "type": "dhcp",
    "routes": [ { "dst": "10.0.0.0/8", "gw": "10.0.0.1" } ]
  },
  "dns": {
    "nameservers": [ "10.0.0.1" ]
  }
}

**Comment by squeed** [comment]
This issue is stale - all of the problems have been fixed in master (and will be released shortly. 

The DHCP plugin, separately, does not currently support a static `routes` field, because there's been no need for it. If you can come up for a good reason for its behavior, please file an issue in the plugins repository.

An important question is how the routes should be merged with those returned from the DHCP server.

**Comment by eyz** [comment]
@squeed do you have links to the merges / commits / PRs for the areas you mentioned, which are fixed in master?
