### ISSUE TITLE
macvlan / ipvlan: IPAM routes / gateway is ignored

### ISSUE THREAD

**Issue by squeed** [containernetworking/cni#336]
The `ptp` interface plugin installs the routes returned by the IPAM plugin. However, neither macvlan or ipvlan do this.

Is there a reason for this discrepancy? Or is it an oversight?

**Comment by squeed** [comment]
This is the root cause for #310.

**Comment by skysec** [comment]
Actually, the problem relies on the specification (SPEC.md): "gateway is the default gateway for this subnet, if one exists. It does not instruct the CNI plugin to add any routes with this gateway: routes to add are specified separately via the routes field. An example use of this value is for the CNI plugin to add this IP address to the linux-bridge to make it a gateway." This is the reason of #310, because in order to change this behaviour, the specification needs to be updated.

**Comment by squeed** [comment]
You're right, I jumped the gun.
