### ISSUE TITLE
Host-Local does not reuse deleted ip addresses

### ISSUE THREAD

**Issue by cizixs** [containernetworking/cni#417]
When using `Host-Local ` ipam, it assigns ip address in specified range, and keeps the last reserved ip address. Next time, it will try to find a available ip in `[last_reserved_ip + 1, end]`, it will print the following error:

    no IP addresses available in network: [networkname]

The problem is, assigned ip address can be recycled(because the container is deleted), but `Host-Local` does not reuse these ip addresses, which is a huge wast of resources.

Is there plan to improve this?

**Comment by rosenhouse** [comment]
I'm surprised to hear this because I thought that we had an [explicit test-case](https://github.com/containernetworking/cni/blob/d5acb12/plugins/ipam/host-local/backend/allocator/allocator_test.go#L117-L127) for IP re-use.

Could you provide more details for how to reproduce the problem?  Please include the network config you're using and which release of CNI exhibits this problem.

**Comment by cizixs** [comment]
@rosenhouse After checking, this is not caused by `cni`.
So I'am closing it, and sorry for the trouble.

**Comment by danielqsj** [comment]
@cizixs Hi, I meet the same issue. What causes this?
