### ISSUE TITLE
Evaluate port mapping

### ISSUE THREAD

**Issue by eyakubovich** [containernetworking/cni#46]
Some containers need to have port mapping between them and the host. The current stance of CNI is that it is outside the scope (and rkt handles port mapping itself). The reasoning behind this is that port mapping is not associated with any particular network but rather is "global" to the container. At the same time port mapping is implemented as a DNAT rule that maps to a _particular_ IP in the container and thus into a network. Therefore it may also make sense to make that a part of the plugin's responsibilities.

**Comment by asridharan** [comment]
Do we have any further insights/discussions on this particular topic? This pretty important from the perspective of orchestration engines such as Mesos since an answer to this question would indicate whether we need to incorporate port mapping as an implementation into the container runt time or use interfaces to pass this information to the plugin. 

Ideally we would like this responsibility to be offloaded to the plugin, reason being that there seems to be cases where the underlying network would like to perform the port mapping instead of relying on the linux kernel. One specific use-case that has come up in the Mesos community discussions is the case where  the data-plane being used is OVS instead of the kernel. In this case setting up iptable rules to perform DNAT might actually be deterimental to the underlying forwarding plane. 

One thought I had was to have port mapping specific plugin, and use "delegation" to allow plugins to offload port mapping to this plugin". Plugins that rely on the underlying data-plane to perform the port-mapping can simply avoid this delegation.

**Comment by rosenhouse** [comment]
Your analysis makes sense.  When this has been discussed in the past, the conversation has gone from "port mapping" to "iptables in general" to "dynamic filter rules" to "maybe CNI needs some kind of dynamic UPDATE like action". 

There's certainly nothing stopping you from building a plugin that sets up port mappings, given some particular NetConf representation of the desired mappings.

I'd question whether delegation is the right way to invoke that plugin, since it requires code changes in the caller.  Instead, it might make sense for the container runtime to just invoke two plugins in a row, passing the output of the first one as input to the second one.

But more discussion or draft PRs would be interesting.

References:
- https://github.com/containernetworking/cni/issues/89#issuecomment-216910419
- https://github.com/containernetworking/cni/issues/151

**Comment by asridharan** [comment]
@rosenhouse is there a way for operators to specify serialization of plugins in the CNI config? Didn't see any documentation on this? 

I am referring to your comment about "container runtime invoking multiple plugins". Currently Mesos doesn't do this. So wondering if this actually a thing?

**Comment by rosenhouse** [comment]
I'm not sure it is formally specified, but runtimes may use `libcni.ConfFiles` which loads plugin configuration from disk [sorted by filename](https://golang.org/pkg/io/ioutil/#ReadDir).  For example, an operator may put configuration files `10_loopback.conf`, `20_bridge.conf` and `30_port_forward.conf` all in the same configuration directory with the expectation that a runtime will execute the referenced plugins in order.

In CloudFoundry we achieve largely the same thing using `filepath.Walk`.

As far as feeding output of one to the input of that next, that is not something I've seen before but we could certainly begin to standardize something.  For example, we could standardize an optional `PrevResult` field on the `NetConf`, and add a function to CNI that did the chaining: pass the `types.Result` of one call as the `PrevResult` field on input to the next.   (In fact, this could be built on top of the `InjectConf` feature I [proposed in #273](https://github.com/containernetworking/cni/pull/273#issuecomment-236663429)).

We've discussed this possible behavior previously, I can't find the issue right now.

**Comment by asridharan** [comment]
I like the idea of the operator being able to specify plugin chains to build more complex CNI configurations. However, not sure why we need the plugins to be aware of the causality of invocation of the plugins, i.e., if we can standardize the JSON to create the causality of invocation the plugins themselves can act independently without knowing where the inputs have originated.

**Comment by rosenhouse** [comment]
That's a good point.  I like the idea of the plugin being simpler, and the complexity of configuration being the responsibility of the container runtime + CNI library.

You could do all of this today using existing features of CNI, but it would be nice to add some helper functions to the library.

**Comment by asridharan** [comment]
@rosenhouse let me backtrack a little. I think I see your point of having the `PrevResult` field standardized in `NetConf`. Had a discussion with @jieyu on how we would support port mapping in a container run time engine such as Mesos and one thing that did pop up was that the JSON to the chained plugin would require information that might be "dependent" on results from invocation of the previous plugin.  E.g., the container IP from invocation of  the bridge plugin might need to be an input to the port mapping plugin (along with other data). So having a field such as `PrevResult` would be necessary to support any kind of chaining. 

Another point that came up was why not make `PrevResult` an array of `types.Result` since then the invocation chain could support a DAG instead of requiring it to be a linear hierarchy? How operators specify this DAG in a CNI setting is an open question, but would make the standard more future proof.

**Comment by dcbw** [comment]
@rosenhouse @asridharan I'd also like to see this become more flexible with CNI, but in the opposite way: I want kubernetes to still handle this via the current hostport code, but in a selectable manner on a per-plugin basis... anyway, perhaps that's not actually relevant to this discussion.

What's probably more relevant are some of the problem associated with port mapping.

1. the mapping should happen at container network setup/teardown time (eg, from a plugin) to minimize race conditions.
2. unfortunately, since ports are node-global resource, the node needs to be aware of all mapped ports of all containers running on the node, since you need to prevent port conflicts
3. the port manager needs to ensure garbage collection happens for containers that are no longer running, even if network teardown doesn't happen.  Yes, this should happen already in kubelet, but do to various codepaths it may not always be the case that network teardown is called when a pod is killed.  This also depends on the runtime.

I think (1) and perhaps (2) will happen when we start passing the PodSpec down to CNI plugins via the extra CNI args, then at least plugins have access to the requested port mapping.  (3) probably requires some kind of long-running process outside the plugin.

**Comment by bboreham** [comment]
> the expectation that a runtime will execute the referenced plugins in order

This would not be my expectation at all.  I would expect at some point platforms (e.g. Kubernetes) will allow the administrator to assign different networks to containers, by naming different CNI config files.

**Comment by asridharan** [comment]
@bboreham your point is valid. In fact in Mesos as well we support "named" CNI networks, and expect a config to be a representation of a single CNI network. 
http://mesos.apache.org/documentation/latest/cni/

Should have added to my earlier comments. The proposal we have for invoking plugins in a chain is to allow a CNI config with the following JSON schema:
```
{
  "name" = "<CNI network>",
  [
     <JSON CNI config for plugin 1>
  ]
  [
     <JSON CNI config for plugin 2>
  ]
}
```
The expectation from the container run time would be, for each plugin, to take the "name" field and concatnate it with the JSON config for a given plugin to create a new JSON dict that will be passed to the CNI plugin. From the CNI plugin the input formats don't change, except for plugin 2 as @rosenhouse had proposed we have the extra `PrevResult` field (derived from the output of plugin 1) injected into `NetConf` of plugin 2.

**Comment by asridharan** [comment]
@dcbw just commenting on your points:

> the mapping should happen at container network setup/teardown time (eg, from a plugin) to minimize race conditions.

Serializing the plugins should take care of this, since they would be invoked during container creatino and network setup.

>unfortunately, since ports are node-global resource, the node needs to be aware of all mapped ports of all containers running on the node, since you need to prevent port conflicts
the port manager needs to ensure garbage collection happens for containers that are no longer running, even if network teardown doesn't happen. Yes, this should happen already in kubelet, but do to various codepaths it may not always be the case that network teardown is called when a pod is killed. This also depends on the runtime.

In Mesos this is solved by treating ports as resources. Its the responsibility of a higher level scheduler such as Marathon reserves ports and is responsible for setting up the `port-mapping` before asking the agent to launch the container.

> the port manager needs to ensure garbage collection happens for containers that are no longer running, even if network teardown doesn't happen. Yes, this should happen already in kubelet, but do to various codepaths it may not always be the case that network teardown is called when a pod is killed. This also depends on the runtime.

Again, in Mesos, since ports are treated as resources they are recycled once the container is destroyed. Just wanted to give an alternative perspective to Kubernetes in case it helps.

**Comment by thockin** [comment]
Another thing to keep in mind when it comes to hostports:  If you use iptables to do the port-forward, the kernels does not prevent a process from opening that port and listen()ing.  This is pretty bad, IMO, since it will never work, but the app/developer can't know that.  Worse, someone could ask for a HostPort that is in use by another app and hijack it.

In kubernetes we open the port and hold it to prevent anyone else from binding to it.  If we can't open the hostport we do not set up the forwarding.  Last I looked, docker does not go this far.

I would LIKE hostports to be "above" CNI plugins but I can't convince myself it is safe.  We already have an IPAM helper plugin.  Does it make sense to have a HostPort helper plugin?

**Comment by asridharan** [comment]
By the way @rosenhouse I realized that while our proposal for chaining CNI plugins is specifically in the context of port mapping, it can have a broader impact, E.g. setting up external load balancers, inserting DNS entries for containers (CNI args).  Would be really great if we can get some feedback on this from the maintainers.

**Comment by thockin** [comment]
> the actual port mapping (setting up iptable rules, or ovs flows or a NAT rule in an external firewall) should be done by the plugin

This does not offer a way to hold the port open to prevent other apps from using it, as far as I can tell.  You need a long-lived process for that.  Likewise it is unfortunate if multiple plugins (all of them?) end up implementing port-forwards.  It's actually a little tricky to get all the corner cases right.

**Comment by asridharan** [comment]
@thockin but the reservation of the port should not be the responsibility of the plugin . As with most CNI plugins, plugins themselves should be stateless. The proposal isn't intended to solve the port reservation problem. In case of Kubernetes it should dealt with "in" Kubernetes and the same goes for Mesos or any other orchestration engine.

**Comment by caseydavenport** [comment]
My general approach to thinking about this has been the port-mappings on the host are outside responsibility of CNI.  However, it seems like a pragmatic solution to add this to CNI given it's something that is a common requirement across orchestrators.

I see two parts - the reservation of the port and the implementation of the actual port mapping (via iptables, whatever).

As others said above, the reservation of the port should be the responsibility of the orchestrator (k8s, mesos) as it needs a long-running process to hold it.

As for the second part, I would _want_ it to work similar to IPAM does at the moment via delegation to another plugin. However, it's a bit clunky because the port-mapping plugin would likely need to know the output from the IPAM plugin, so it does sort of want to be "chained" if you will.

**Comment by CaoShuFeng** [comment]
Hi, I am starting to fix this according to @caseydavenport  's suggestion:

>> As for the second part, I would want it to work similar to IPAM does at the moment via delegation to another plugin. 

Can someone assign this issue to me?

**Comment by bboreham** [comment]
Interesting: Mesos have implemented a port mapper plugin.
http://mesos.apache.org/documentation/latest/cni/#a-port-mapper-plugin
https://github.com/apache/mesos/tree/master/src/slave/containerizer/mesos/isolators/network/cni/plugins/port_mapper

**Comment by bboreham** [comment]
Work progressing at https://github.com/containernetworking/plugins/pull/1

**Comment by squeed** [comment]
This happened.
