### ISSUE TITLE
Test killed with quit: ran too long (10m0s)

### ISSUE THREAD

**Issue by PhillWide** [containernetworking/cni#739]
Hi, 
Im trying to deploy podman on Debian 10 and therefore installing CNI plugins. 
I installed them with go 1.11.6 and ran the test, but that failed with timeout.

And therefore running podman containers fails:
root@openstack-workstation:/srv/go/plugins# podman run -it alpine /bin/sh
Error: error configuring network namespace for container 48409c7374c67785a6e46f71be0deaeafc9ad8cf29f12d7491086e7e5e97a2fe: Missing CNI default network

**Comment by jellonek** [comment]
Do you have any configuration in `/etc/cni/net.d/`?
It looks as this can be podman specific error (I'm not using it) - have you looked on https://www.redhat.com/sysadmin/container-networking-podman ?

**Comment by PhillWide** [comment]
Yes, I have the configuration provided in the install instructions. At first I thought the same, that I might have reconfigured podman. That is why I ran the test_linux.sh scripts provided with the plugins (now I think of it, what repository would be more appropriate to place this issue in, but it has been a long day and I placed it here) And there lies the problem I think. Iam not able to succesfully run the tests for the scripts. It just ends after 10 minutes of running (title)

**Comment by PhillWide** [comment]
I figured out the issue with podman. Not with the test it self, but I bet I did something wrong in the settup. Thanks for the help.

**Comment by aleks-mariusz** [comment]
could you please share WHAT you did wrong because someone else may have as well and seeing just that you fixed it with no details is not very helpful to others

**Comment by PhillWide** [comment]
> could you please share WHAT you did wrong because someone else may have as well and seeing just that you fixed it with no details is not very helpful to others

If I remember correctly I copied the CNI plugins to the wrong folder (error in my Ansible role). Also, I'm thinking I had a different cni_default_network that podman, but I cannot figure out why. I have an Ansible role for the installation now. I plan to upload it to ansible galaxy at some point.

**Comment by aleks-mariusz** [comment]
thanks PhilWide, i finally got this working as well.. for me i also moved the plugins to `/opt/cni/bin` and loading [this version](https://github.com/containers/libpod/blob/master/cni/87-podman-bridge.conflist) of the conf file into the `/etc/cni/net.d` directory.. i started with the `podman network create` command, that worked, so then i deleted the new network and just did `podman network ls` to see what the default would be, afterwards i may have also tried to create it using `ip link add cni-podman0 type bridge`.. at the end of all the fiddling it did work so not sure which step exactly it was but hope this helps someone else.. 

i was setting up/[compiled podman](https://computingforgeeks.com/how-to-install-podman-on-debian/) actually for my raspberry pi Model B (1st gen) because docker is needlessly bloated/unnecessary as i can use the built-in linux kernel namespaces/cgroups to do the same thing..
