### ISSUE TITLE
ptp: host veth interface has no IP address assigned

### ISSUE THREAD

**Issue by steveeJ** [containernetworking/cni#77]
Happening on my laptop since a recent system upgrade. It's unclear what's causing this, and no error is produced when e.g. using the scripts to enter a new namespace created by CNI.

The journal shows the following error messages during the CNI plugin setup:

```
Nov 11 18:26:32 steveej-laptop NetworkManager[955]: <warn>  (veth9a2ffe01): failed to find device 63 'veth9a2ffe01' with udev
```

My current NetworkManager version 1.0.6

**Comment by steveeJ** [comment]
I haven't bisected nor searched for the exact NetworkManager version that introduced this behavior, but I've reproduced the problem with a manually created veth interface. My current NetworkManager version 1.0.6 will launch a DHCP client on all created interfaces, removing any previously set IP address. This prevents at least the bridge and ptp CNI plugins from working.

Telling NM to ignore a pattern of device names seems like a good idea on my laptop:
```
$ cat /etc/NetworkManager/NetworkManager.conf 
[main]
plugins=keyfile

[keyfile]
hostname=steveej-laptop
unmanaged-devices=interface-name:veth*;interface-name:virbr*;interface-name:br*;interface-name:*vbox*;interface-name:*cni*;vboxnet0

[logging]
level=WARN
```

**Comment by dcbw** [comment]
@steveeJ  (also @lkundrak for more NM perspective)

First, the unmanaged-devices line there doesn't need anything in it that's not a 'veth' device.  The problem here is likely *only* related to veth since they were specially treated in NM for a while, which I'll talk about below.  But bridge/bond/team/etc created outside NM should not be touched by NM at all, and indeed I've never had a problem with those and I run NM all the time for container/kubernetes/openshift/flannel development.

For veth devices, you should have a /usr/lib/udev/rules.d/85-nm-unmanaged.rules file on your system that automatically unmanages certain devices that cannot be distinguished from real physical ethernet, like vboxnet, vmware, parallels, and even veth.  This file should make oyur  unmanaged-devices line completely unecessary.

Can you confirm you have that file?  Could you also run 'nmcli g log level debug' and then reproduce the problem so we can figure out what's going on?

For example, I created a veth pair with "ip link add type veth" and then immediately looked at udev:

sudo udevadm info --export-db | less
...
P: /devices/virtual/net/veth1
E: DEVPATH=/devices/virtual/net/veth1
E: ID_MM_CANDIDATE=1
E: ID_NET_DRIVER=veth
E: ID_NET_LINK_FILE=/usr/lib/systemd/network/99-default.link
E: IFINDEX=31
E: INTERFACE=veth1
E: NM_UNMANAGED=1  <-----
E: SUBSYSTEM=net
E: SYSTEMD_ALIAS=/sys/subsystem/net/devices/veth1
E: TAGS=:systemd:
E: USEC_INITIALIZED=38880144085

and also 'nmcli dev':
DEVICE      TYPE      STATE         CONNECTION     
veth0       ethernet  unmanaged     --               
veth1       ethernet  unmanaged     --              

If the device is in 'unmanaged' state, NM will never touch it until you tell NM to do something explicitly.

**Comment by dcbw** [comment]
I see the error from the first comment now, which may have an effect on whether the udev rules for unmanaging get applied; debug logs from NM would be quite useful here as described above.

**Comment by steveeJ** [comment]
@dcbw I reverted to the original config and collected the logs for you to analyze: https://gist.github.com/steveeJ/fd6d0c1375457ff09958

Let me know if there's anything else you need.

**Comment by dcbw** [comment]
Ok, the "failed to find ... with udev" is a red-herring, since it's found later by udev and NM doesn't do anything with it until the device is found by udev.  Continuing to investigate...

**Comment by dcbw** [comment]
@steveeJ can you confirm that you have the /usr/lib/udev/rules.d/85-nm-unmanaged.rules file?  Also, after you modified NetworkManager.conf, did you restart NetworkManager at all?  That file isn't monitored so it requires either a restart or (with NM 1.2+) SIGHUP to notice changes.

**Comment by dcbw** [comment]
Also, please run:

udevadm info --export-db

and look for the sections for veth pairs.  In those sections, do you see NM_UNMANAGED=1 or is that missing?

**Comment by steveeJ** [comment]
@dcbw: 

> can you confirm that you have the /usr/lib/udev/rules.d/85-nm-unmanaged.rules file

The file https://gist.github.com/steveeJ/fd6d0c1375457ff09958#file-85-nm-unmanaged-rules is active on my system, it's not at the exact path you mention because of NixOS works. I've got several NM installations stored on the disk. 

> udevadm info --export-db

https://gist.github.com/steveeJ/fd6d0c1375457ff09958#file-nmcli-dev-log is complete, so `NM_UNMANAGED=1` is missing.

> did you restart NetworkManager at all? That file isn't monitored so it requires either a restart or (with NM 1.2+) SIGHUP to notice changes

Yes, I restarted NM to make sure the changes take effect, and they did. But Maybe you didn't read this part of my comment that contained the logs?
> I reverted to the original config and collected the logs for you to analyze: https://gist.github.com/steveeJ/fd6d0c1375457ff09958

I state that I switched *back* to the original configuration to collect the debug logs for you.

**Comment by dcbw** [comment]
@steveeJ Ok, I'm a bit confused.  You stated that NM 1.0.6 has the problem where it will manage (and run DHCP) on veth interfaces.  Is that the "original config" you reference?  If not, what is the original config and what config did you switch back from?  Basically, what config works and what config doesn't work?
