### ISSUE TITLE
Expected runtime Behavior if CNI ADD call fails

### ISSUE THREAD

**Issue by ninzavivek** [containernetworking/cni#775]
I want to ask if there is an expectation on the container runtime with regards to calling CNI DEL, if CNI ADD fails for some reason.

As per this:

https://github.com/containernetworking/cni/blob/master/SPEC.md#general-considerations

The container runtime must order ADD and DEL operations for a container, such that ADD is always eventually followed by a corresponding DEL. DEL may be followed by additional DELs but plugins should handle multiple DELs permissively (i.e. plugin DEL should be idempotent).

**Comment by bboreham** [comment]
Interesting question. My first instinct was to say "no".

However it is specified that DEL must be called [for a list](https://github.com/containernetworking/cni/blob/master/SPEC.md#network-configuration-list-error-handling), and I would expect the single-plugin case to behave the same as a list of 1. So that makes it "yes".

**Comment by squeed** [comment]
Should we reopen this? We could update the spec for 1.0 that says that a failed add SHOULD (as much as possible) get a delete. If there's a desire for it.

Yes, a plugin SHOULD also clean up after itself if adding fails, but it could also segfault.

**Comment by yylt** [comment]
Hi, I miss the problem like this issue described

### environment
- containerd 1.4.0
- k8s 1.16.6

### flannel confguation

```
{
  "name":"cni0",
  "cniVersion":"0.3.1",
  "plugins":[
    {
      "type":"flannel",
      "delegate":{
        "forceAddress":true,
        "hairpinMode": true,
        "isDefaultGateway":true
      }
    },
    {
      "type":"portmap",
      "capabilities":{
        "portMappings":true
      }
    }
  ]
}
```

containerd log 

```
Oct 13 19:57:26 node-6.domain.tld containerd[7401]: time="2020-10-13T19:57:26.657923748+08:00" level=info msg="shim disconnected" id=48579e8be48f4e17144c81e6750947513bd790985c3513a78a84d3569d94b33c
Oct 13 19:57:27 node-6.domain.tld containerd[7401]: time="2020-10-13T19:57:27.000650503+08:00" level=error msg="Failed to destroy network for sandbox \"48579e8be48f4e17144c81e6750947513bd790985c3513a78a84d3569d94b33c\"" error="delegateDel: error invoking ConflistDel - \"cni0\": conflistDel: error in getting result from DelNetworkList: could not teardown ipv4 snat: running [/usr/sbin/iptables -t nat -N CNI-SN-789e45a28000a6e5f5d67 --wait]: exit status 4: iptables: Resource temporarily unavailable.\n"
```

the problem is ip leaked when container create failed, because portmap plugin deleted failed, thus result in flannel do not invoked, and host-local plugin can not destory ip which had allocated

should we call `DelNetworkList` for a list?

[go-cni](https://github.com/containerd/go-cni/issues/60)
