### ISSUE TITLE
ParsePrevResult uses wrong cni version

### ISSUE THREAD

**Issue by anguslees** [containernetworking/cni#862]
I'm a bit lost in the version conversion code, so I might be complete wrong here.  But:

I think `version.ParsePrevResult` uses `conf.CNIVersion`, whereas it _should_ use `conf.RawPrevResult["cniVersion"]` here:
https://github.com/containernetworking/cni/blob/5725f278690e2167982c25a08d1ff63247bb3753/pkg/version/version.go#L83

I think this means that chained plugins that try to read the prevResult will abort unless the prevResult version matches the conf version.  There's no real reason that has to be the case, and indeed it's highly likely that the config and/or the previous CNI plugin in the chain are not all upgraded to 1.0.0 at the same moment.

**Comment by mars1024** [comment]
If CNI plugins are not upgraded to 1.0.0, then invoking plugins with a network config which `cniVersion == 1.0.0` will break in result conversion or result print, the two phases are both before parsing previous results.

**Comment by anguslees** [comment]
So .. everything (conf file, all plugins) has to be upgraded simultaneously to 1.0.0?
Now I'm even more confused :)  Why do we have all this version conversion code then?

**Comment by jayunit100** [comment]
can we deduce the two issues :)

**Comment by dcbw** [comment]
@anguslees partly because the places that read/use a Result don't always have access to the config, nor need to parse it. If we guarantee (which libcni does) that plugins always return a Result of the same version as the input config, and we have a `cniVersion` in the Result, then runtimes and other plugins parsing Result/prevResult don't need to pass two things around internally.

`I think this means that chained plugins that try to read the prevResult will abort unless the prevResult version matches the conf version. There's no real reason that has to be the case, and indeed it's highly likely that the config and/or the previous CNI plugin in the chain are not all upgraded to 1.0.0 at the same moment.`

But second, and directly responding to this question, CNI requires that all plugins in a chain support the cniVersion specified in the input configuration and that they all return a Result in the same version as that config. A large reason is to keep things clear, simple to understand, and reduce edge-cases that would cause failures. If a plugin can accept a given config version, it is guaranteed to be able to output that config version, and so it shouldn't have a problem doing so.

I think it would be more confusing for both plugin implementers and users to have a plugin accept cniVersion=0.4.0 but only be able to output Result 0.2.0 or 1.0.0; if the plugin accepts 0.4.0 the surely it has been updated to be able to output 0.4.0 too.

Second, chained plugins that require prevResult (0.4.0 and higher IIRC) wouldn't work correctly with plugins that dont' output a 0.4.0 or higher result, because those plugins don't echo through prevResult. Specifying a config verison of 0.4.0 and requiring all plugins to accept that version and output the same result version ensures that all plugins in the chain get the input they expect.

Does that help clarify things?

I think you did find a bug with the CNIVersion/cniVersion thing though :)

**Comment by dcbw** [comment]
> So .. everything (conf file, all plugins) has to be upgraded simultaneously to 1.0.0?

Here, the answer is yes. If not all plugins in the chain support 1.0.0, then you cannot ensure the chain will work correctly as a whole. If you bump the conf version to 1.0.0, then clearly there is some feature or change the admin wants from 1.0.0. If the plugins in the chain don't support 1.0.0, there is no guarantee that you'll get what you want out of it.

**Comment by anguslees** [comment]
> Does that help clarify things?

That explanation helped enormously, thanks.  👍
